### ISSUE TITLE
Errors while moving through the readme

### ISSUE THREAD

**Issue by jason-mehmel** [nlbao/pocket_stats#18]
Hi there... I encountered the following errors when trying to follow the readme:

```
$ make setup
pip install pytest pytest-cov flake8 twine freezegun
make: pip: Command not found
make: *** [Makefile:2: setup] Error 127
```

I tried to continue and used **python3 -m pocket_stats fetch-data --overwrite_cache** which looked like it worked, but:

$ python -m pocket_stats webapp
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 114, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/jason/pocket_stats/pocket_stats/__main__.py", line 10
    def fetch_data(offset: int, limit: int, overwrite_cache: bool) -> None:
                         ^
SyntaxError: invalid syntax

Not sure what I'm doing wrong. Is the makefile not working? I'm looking at the errors there and wondering if it's leading to the problem in the webapp.

**Comment by jason-mehmel** [comment]
Note! I just checked my Ubuntu system for pip and couldn't find it, but did find **pip3.**

I changed the makefile to indicate pip3 instead of pip and it seemed to install correctly!

But I'm still having the same problem trying to run the webapp.

**Comment by jason-mehmel** [comment]
Also, I tried running **python3** as the command instead of just **python** (not sure of the difference) and got this:

python3 -m pocket_stats webapp
2021-01-11 19:02:40,915 - [INFO] - filelock - Lock 139925194099632 acquired on /home/jason/.cache/python-tldextract/3.8.5.final__usr__7d8fdf__tldextract-3.1.0/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2021-01-11 19:02:40,915 - [INFO] - filelock - Lock 139925194216880 acquired on /home/jason/.cache/python-tldextract/3.8.5.final__usr__7d8fdf__tldextract-3.1.0/urls/62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2021-01-11 19:02:41,121 - [INFO] - filelock - Lock 139925194216880 released on /home/jason/.cache/python-tldextract/3.8.5.final__usr__7d8fdf__tldextract-3.1.0/urls/62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2021-01-11 19:02:41,135 - [INFO] - filelock - Lock 139925194099632 released on /home/jason/.cache/python-tldextract/3.8.5.final__usr__7d8fdf__tldextract-3.1.0/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jason/pocket_stats/pocket_stats/__main__.py", line 35, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jason/pocket_stats/pocket_stats/__main__.py", line 21, in webapp
    app = create_app()
  File "/home/jason/pocket_stats/pocket_stats/visualization.py", line 219, in create_app
    domain_counts_plot(data),
  File "/home/jason/pocket_stats/pocket_stats/visualization.py", line 154, in domain_counts_plot
    top_pairs = list(get_domain_counts(data).items())  # both unread + archived
  File "/home/jason/pocket_stats/pocket_stats/data.py", line 162, in get_domain_counts
    return Counter(get_domain_from_url(record['resolved_url'])
  File "/usr/lib/python3.8/collections/__init__.py", line 552, in __init__
    self.update(iterable, **kwds)
  File "/usr/lib/python3.8/collections/__init__.py", line 637, in update
    _count_elements(self, iterable)
  File "/home/jason/pocket_stats/pocket_stats/data.py", line 162, in <genexpr>
    return Counter(get_domain_from_url(record['resolved_url'])
KeyError: 'resolved_url'

**Comment by nlbao** [comment]
Hi @jason-mehmel, that command (python3 ...) has been replaced by another command in the latest version (0.3.0). Could you try to:
1. Uninstall the old package: `pip3 uninstall pocket-stats`
2. Reinstall it.
3. Run `gunicorn --workers 1 'pocket_stats.app:server' -b :8077`

Btw, I have deployed a simple web interface at https://pocket-stats.nlbao.page , in case you don't want to run the app yourself.
