### ISSUE TITLE
[GCP] OSError: No such file or directory: '/root/nltk_data/corpora/stopwords/english' 

### ISSUE THREAD

**Issue by nlbao** [nlbao/pocket_stats#20]
```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/env/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/opt/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/pocket_stats/app.py", line 3, in <module>
    from visualization import create_app
  File "/srv/pocket_stats/visualization.py", line 13, in <module>
    from data import get_data, count_words_in_title, get_word_counts, get_reading_time, get_average_readed_word
  File "/srv/pocket_stats/data.py", line 23, in <module>
    invalid_words = stopwords.words('english')
  File "/env/lib/python3.7/site-packages/nltk/corpus/reader/wordlist.py", line 23, in words
    for line in line_tokenize(self.raw(fileids))
  File "/env/lib/python3.7/site-packages/nltk/corpus/reader/wordlist.py", line 32, in raw
    return concat([self.open(f).read() for f in fileids])
  File "/env/lib/python3.7/site-packages/nltk/corpus/reader/wordlist.py", line 32, in <listcomp>
    return concat([self.open(f).read() for f in fileids])
  File "/env/lib/python3.7/site-packages/nltk/corpus/reader/api.py", line 208, in open
    stream = self._root.join(file).open(encoding)
  File "/env/lib/python3.7/site-packages/nltk/data.py", line 337, in join
    return FileSystemPathPointer(_path)
  File "/env/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/nltk/data.py", line 315, in __init__
    raise IOError("No such file or directory: %r" % _path)
OSError: No such file or directory: '/root/nltk_data/corpora/stopwords/english'
```

**Comment by nlbao** [comment]
Resolved in https://github.com/nlbao/pocket_stats/commit/f25a75d7df861cc33373aa634c9c568c6e7c961a
