### ISSUE TITLE
[GCP] FileExistsError: [Errno 17] File exists: '/root/nltk_data/corpora/stopwords' 

### ISSUE THREAD

**Issue by nlbao** [nlbao/pocket_stats#21]
```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/opt/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/pocket_stats/app.py", line 5, in <module>
    from visualization import create_app
  File "/workspace/pocket_stats/visualization.py", line 13, in <module>
    from data import get_data, count_words_in_title, get_word_counts, get_reading_time, get_average_readed_word
  File "/workspace/pocket_stats/data.py", line 27, in <module>
    download_ntlk()
  File "/workspace/pocket_stats/data.py", line 24, in download_ntlk
    nltk.download('stopwords')
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/nltk/downloader.py", line 779, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/nltk/downloader.py", line 643, in incr_download
    for msg in self._download_package(info, download_dir, force):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/nltk/downloader.py", line 737, in _download_package
    for msg in _unzip_iter(filepath, zipdir, verbose=False):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/nltk/downloader.py", line 2252, in _unzip_iter
    zf.extractall(root)
  File "/opt/python3.7/lib/python3.7/zipfile.py", line 1636, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/opt/python3.7/lib/python3.7/zipfile.py", line 1686, in _extract_member
    os.mkdir(targetpath)
FileExistsError: [Errno 17] File exists: '/root/nltk_data/corpora/stopwords'
```

**Comment by nlbao** [comment]
Resolved in https://github.com/nlbao/pocket_stats/commit/f25a75d7df861cc33373aa634c9c568c6e7c961a
